DROP TABLE IF EXISTS workouts;
DROP TABLE IF EXISTS lower1;
DROP TABLE IF EXISTS lower2;
DROP TABLE IF EXISTS lower3;
DROP TABLE IF EXISTS upper1;
DROP TABLE IF EXISTS upper2;
DROP TABLE IF EXISTS upper3;
DROP TABLE IF EXISTS fullbody1;
DROP TABLE IF EXISTS fullbody2;
DROP TABLE IF EXISTS fullbody3;
DROP TABLE IF EXISTS chest;
DROP TABLE IF EXISTS back;
DROP TABLE IF EXISTS arms;
DROP TABLE IF EXISTS legs;
DROP TABLE IF EXISTS Difficulty;
DROP TABLE IF EXISTS num_sets;
DROP TABLE IF EXISTS reps;
DROP TABLE IF EXISTS shoulders;
;


